version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      - APP_ENV=${APP_ENV}
    volumes:
      - .:/code
      - logvolume01:/var/log
      - ./postgres_data/:/var/lib/postgresql/data/
    links:
      - database
    depends_on:
      - database
  redis:
    image: redis
  database:
    image: 'postgres:latest'
    container_name: postgres_db_container
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: yourUserDBName
        POSTGRES_PASSWORD: yourUserDBPassword
        POSTGRES_DB: yourDBName
  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A app.celery_task worker -l INFO
    volumes:
      - ./:/app
    environment:
      - APP_ENV=${APP_ENV}
    links:
      - redis
    depends_on:
      - redis
      - database
volumes:
  logvolume01: {}
  postgres_data: {}