version: "3.9" # optional since v1.27.0
services:
  redis:
      image: redis
  database:
    image: 'postgres:latest'
    container_name: postgres_db_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: yourUserDBName
      POSTGRES_PASSWORD: yourUserDBPassword
      POSTGRES_DB: yourDBName
  migration:
      build: .
      environment:
        - APP_ENV=${APP_ENV}
      command: flask db upgrade
      depends_on:
        - database
  worker:
    build: .
    hostname: worker
    # entrypoint: celery
    # command: -A app.celery_task worker -l INFO
    command: celery -A app.celery_task worker -l INFO
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - redis
      - database
      - migration
  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      - APP_ENV=${APP_ENV}
    links:
      - database
    depends_on:
      - database
      - redis
      - migration
  api-beat:
   build: .
   command: celery -A app.celery_task beat -l INFO
   environment:
     - APP_ENV=${APP_ENV}
   depends_on:
     - redis
     - database
     - migration
